import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider} from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import {routing} from '@/i18n/routing';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params}) {
  const messages = await getMessages();

  const {locale} = await params;

  console.log(`Loading translations for locale: ${locale}`);

  console.log('messages', messages)

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <NextIntlClientProvider
      locale={locale}
      messages={messages}
    >
      <>
        <>{children}</>
      </>
    </NextIntlClientProvider>
    </body>
    </html>
  );
}
